# Generated by Django 6.0.3 on 2026-03-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('admin', 'Administrator')], default='citizen', max_length=20)),
                ('sector', models.CharField(blank=True, choices=[('infrastructure', 'Infrastructure'), ('utilities', 'Utilities'), ('safety', 'Safety'), ('health', 'Health'), ('admin', 'Administration')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
