# Generated by Django 4.2.30 on 2026-04-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_duplicate_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_add_profile_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('status_change', 'Промена на статус'), ('report_submitted', 'Поднесена пријава'), ('report_assigned', 'Доделена пријава'), ('system', 'Системско известување')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notification_user_read_idx'), models.Index(fields=['created_at'], name='notification_created_idx')],
            },
        ),
    ]
