# Generated by Django 4.2.29 on 2026-05-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_avatar'),
        ('accounts', '0005_usernotification'),
    ]

    operations = [
    ]
