# Generated by Django 4.2.30 on 2026-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('status_change', 'Промена на статус'), ('report_assigned', 'Доделена пријава'), ('system', 'Системско известување')], max_length=50),
        ),
    ]
