# Generated by Django 4.2.30 on 2026-05-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usernotification_type'),
        ('accounts', '0006_merge_0004_userprofile_avatar_0005_usernotification'),
    ]

    operations = [
    ]
