# Generated by Codex on 2026-05-03

from django.db import migrations, models

import apps.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_0004_userprofile_avatar_0005_usernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="municipality",
            field=models.CharField(
                blank=True,
                choices=apps.reports.models.MUNICIPALITY_CHOICES,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
