# Generated by Django 4.2.30 on 2026-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportcategory_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='municipality',
            field=models.CharField(blank=True, choices=[('aerodrom', 'Аеродром'), ('aracinovo', 'Арачиново'), ('berovo', 'Берово'), ('bitola', 'Битола'), ('bogdanci', 'Богданци'), ('bogovinje', 'Боговиње'), ('bosilovo', 'Босилово'), ('brvenica', 'Брвеница'), ('butel', 'Бутел'), ('valandovo', 'Валандово'), ('vasilevo', 'Василево'), ('veles', 'Велес'), ('vevchani', 'Вевчани'), ('vinica', 'Виница'), ('vrapchishte', 'Врапчиште'), ('gazi_baba', 'Гази Баба'), ('gevgelija', 'Гевгелија'), ('gjorche_petrov', 'Ѓорче Петров'), ('gostivar', 'Гостивар'), ('gradsko', 'Градско'), ('debar', 'Дебар'), ('debarca', 'Дебарца'), ('delchevo', 'Делчево'), ('demir_hisar', 'Демир Хисар'), ('demir_kapija', 'Демир Капија'), ('dojran', 'Дојран'), ('dolneni', 'Долнени'), ('zhelino', 'Желино'), ('zelenikovo', 'Зелениково'), ('zrnovci', 'Зрновци'), ('ilinden', 'Илинден'), ('jegunovce', 'Јегуновце'), ('kavadarci', 'Кавадарци'), ('karbinci', 'Карбинци'), ('karposh', 'Карпош'), ('kichevo', 'Кичево'), ('kisela_voda', 'Кисела Вода'), ('kochani', 'Кочани'), ('konche', 'Конче'), ('kratovo', 'Кратово'), ('kriva_palanka', 'Крива Паланка'), ('krivogashtani', 'Кривогаштани'), ('krushevo', 'Крушево'), ('kumanovo', 'Куманово'), ('lipkovo', 'Липково'), ('lozovo', 'Лозово'), ('makedonska_kamenica', 'Македонска Каменица'), ('makedonski_brod', 'Македонски Брод'), ('mavrovo_rostushe', 'Маврово и Ростуше'), ('mogila', 'Могила'), ('negotino', 'Неготино'), ('novaci', 'Новаци'), ('novo_selo', 'Ново Село'), ('ohrid', 'Охрид'), ('petrovec', 'Петровец'), ('pehchevo', 'Пехчево'), ('plasnica', 'Пласница'), ('prilep', 'Прилеп'), ('probishtip', 'Пробиштип'), ('radovish', 'Радовиш'), ('rankovce', 'Ранковце'), ('resen', 'Ресен'), ('rosoman', 'Росоман'), ('saraj', 'Сарај'), ('sveti_nikole', 'Свети Николе'), ('skopje', 'Град Скопје'), ('sopishte', 'Сопиште'), ('staro_nagorichane', 'Старо Нагоричане'), ('struga', 'Струга'), ('strumica', 'Струмица'), ('studenichani', 'Студеничани'), ('tearce', 'Теарце'), ('tetovo', 'Тетово'), ('centar', 'Центар'), ('centar_zhupa', 'Центар Жупа'), ('chair', 'Чаир'), ('chashka', 'Чашка'), ('cheshinovo_obleshevo', 'Чешиново-Облешево'), ('chucher_sandevo', 'Чучер-Сандево'), ('shtip', 'Штип'), ('shuto_orizari', 'Шуто Оризари')], default='', max_length=100),
        ),
    ]
