# Generated by Django 6.0.3 on 2026-04-27 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_municipality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority'], name='report_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['latitude'], name='report_latitude_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['longitude'], name='report_longitude_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['sector', 'status'], name='report_sector_status_idx'),
        ),
    ]
