# Generated by Django 6.0.3 on 2026-04-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_report_report_priority_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["is_duplicate"], name="report_is_duplicate_idx"),
        ),
    ]

