# Generated by Django 6.0.3 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_duplicate_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
