# Generated by Django 4.2.29 on 2026-05-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportstatushistory'),
        ('reports', '0007_report_duplicate_flags'),
    ]

    operations = [
    ]
