# Generated by Django 4.2.30 on 2026-05-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_merge_20260501_1815'),
        ('reports', '0008_report_deleted_at_report_is_deleted'),
    ]

    operations = [
    ]
