# Generated by Django 4.2.30 on 2026-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
