# Generated by Django 4.2.30 on 2026-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Испратено'), ('failed', 'Неуспешно'), ('pending', 'Во чекање')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('status_change', 'Промена на статус'), ('report_submitted', 'Поднесена пријава'), ('bulk', 'Масовно известување')], max_length=50),
        ),
    ]
